/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package offline;

import java.awt.event.*;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JTextArea;

/**
 *
 * @author sanjewa
 */
public class IntFace extends javax.swing.JFrame {

    static String[] arraysent1;
    static String cword=null;
	/*
	** initialize hashmap to store data
	*/
      private static HashMap<String,String> database = new HashMap<String,String>();
	
      
        /*
	** synchronize saving data in database to prevent data race
	*/
	  private static void put(String name , String number){
		synchronized (database){
			database.put(name,number);
		}
  	}	
  
  	/*
	** synchronize saved data in database to get data
	*/
	  private static String get(String name){
		synchronized (database){
			return database.get(name);
		}
	    }	
    /**
     * Creates new form IntFace
     */
    public IntFace() {
        initComponents();
             
    }
    
    public void findWord(){   
         int i;
		for(i=0;i<arraysent1.length;i++){
			   if(get(arraysent1[i]) != null){
			    if(cword != null)
			   	 cword = cword.concat(get(arraysent1[i]) + " ");
			   else {
			   	cword = get(arraysent1[i]);
			   	 cword = cword.concat(" ");
			   }
			   
			}    
		}       
          
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setText("Enter your sentence");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);              
		    jTextArea1.setText(null);
		    String text = jTextField1.getText();
		    jTextArea1.append(text + "\n");
		    jTextField1.selectAll();
          	  //jTextField1.setText(null);   
            /*....split text with space and set to array....*/  
            	  arraysent1 = text.split(" ");  
            	   findWord();
		 jTextArea1.append(cword + "\n");             
       		 cword = null;
            }
        });

        jButton1.setText("Go");
       jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            	
            	jTextArea1.setText(null);
                String text = jTextField1.getText();
                jTextArea1.append(text + "\n");
                jTextField1.selectAll();                       
                //jTextField1.setText(null);
                
             
		
           	
            /*....split text with space and set to array....*/  
                   arraysent1 = text.split(" ");    
                 findWord();
		 jTextArea1.append(cword + "\n");    
		 cword = null;
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    //..........work with button ..................///*
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
       /* jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
           
                jTextArea1.setText(null);
                String text = jTextField1.getText();
                jTextArea1.append(text + "\n");
                jTextField1.selectAll();                       
                //jTextField1.setText(null);
                    jTextArea2 = jTextArea1;
            /*....split text with space and set to array..../  
                   arraysent1 = text.split(" ");    
                
getdh();
               /* for(String w:arraysent1){  
                    jTextArea1.append(w + "\n");  
               }/     
            }
        });*/
      
    }//GEN-LAST:event_jButton1ActionPerformed
    
    //...........work with enter key..............//
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
     /* jTextField1.addActionListener((ActionEvent evt1) -> {
           
            jTextArea1.setText(null);
            String text = jTextField1.getText();
            jTextArea1.append(text + "\n");
            jTextField1.selectAll();
            //jTextField1.setText(null);    
           
            /*....split text with space and set to array..../  
              arraysent1 = text.split(" ");  
              
              /*  for(String w:arraysent1){  
                    jTextArea1.append(w + "\n");  
               }  /
            
        });*/
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>
        
        put("I","mama");
        put("am","sitinawa");
        put("going","yamin");
        put("home","gedara");
        /* Create and display the form */
        IntFace obj = new IntFace();
       // obj.setVisible(true);
        
        java.awt.EventQueue.invokeLater(() -> {
            obj.setVisible(true);   
          
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
